[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ascmhl-generator"
version = "0.1.0"
description = "Generate ASC MHL manifests + always verify a directory"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "ascmhl",
]

[project.scripts]
ascmhl-gen = "ascmhl_generator.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]