[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ascmhl-tool"
version = "0.1.0"
description = "ascmhl generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["xxhash>=3.4.1"]

[project.scripts]
make-manifest = "manifest_tool.cli:main"